import random

def main():
    length = int(input("Enter the length of the password: "))
    generator(length)

def data():
    small_letters = 'abcdefghijklmnopqestuvwxyz'
    capital_letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    special_characters = '~!@#$%^&*'
    test = small_letters + capital_letters + special_characters
    return test

def generator(length):
    password = ""
    for i in range(length):
        rand = random.randint(0, len(data()))
        password += data()[rand]
    print("Your Autogenerated password: " + password)

main()